networks:
  default:
    driver: bridge
    name: roboshop

volumes: #for databases - use nammed volumes - stateful application
  mongodb:
  mysql:
  redis:
  rabbitmq:
  
services:
  mongodb:
    image: aneelp/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db  # give volume name and enter path for mount the volume
  
  catalogue:
    image: aneelp/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  
  cart:
    image: aneelp/cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue

  user:
    image: aneelp/user:v1
    container_name: user
    depends_on:
      - mongodb
      - redis

  mysql:
    image: aneelp/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  
  shipping:
    image: aneelp/shipping:v1
    container_name: shipping
    depends_on:
      - mysql
      - cart

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq:var/lib/rabbitmq 
        
  payment:
    image: aneelp/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
      - cart
      - user
      - rabbitmq
  
  frontend:
    image: aneelp/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - cart
      - user
      - shipping
      - payment




