networks:
  default:
    driver: bridge
    name: roboshop

volumes: #for databases - use nammed volumes - stateful application
  mongodb:
  mysql:
  redis:
  rabbitmq:
  
services:
  mongodb:
    image: aneelp/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db  # give volume name and enter path for mount the volume
  
  catalogue:
    image: aneelp/catalogue:v1
    container_name: catalogue

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis:/data
  
  cart:
    image: aneelp/cart:v1
    container_name: cart

  user:
    image: aneelp/user:v1
    container_name: user

  mysql:
    image: aneelp/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  
  shipping:
    image: aneelp/shipping:v1
    container_name: shipping

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
      - rabbitmq:var/lib/rabbitmq  
        
  payment:
    image: aneelp/payment:v1
    container_name: payment
    environment:
     CART_HOST: cart
  
  frontend:
    image: aneelp/frontend:v1
    container_name: frontend




